---
dependency:
  name: galaxy
  options:
    role-file: ../../roles/requirements.yml
    requirements-file: ../../collections/requirements.yml
driver:
  name: docker
platforms:
  - name: instance-ubuntu
    image: "geerlingguy/docker-ubuntu2204-ansible:latest"
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
verifier:
  name: ansible
