---
name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node (semantic-release runtime)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install semantic-release
        run: |
          npm --version || (sudo apt-get update && sudo apt-get install -y npm)
          npm install -D semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/github
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
